### ISSUE TITLE
Ex43.3.jl

### ISSUE THREAD

**Issue by OVGULIU** [PtFEM/PtFEM.jl#10] opened 2019-11-29 17:01 UTC
**In Ex43.3.jl:**

ERROR: LoadError: BoundsError: attempt to **access 4×4 Array{Float64,2} at index [5, 4]**

**Comment by goedman** [comment] 2019-11-29 18:38
Interesting, that definitely is a bug. I guess this might be because of recent changes in sparse matrice? I'll have a look.

**Comment by goedman** [comment] 2019-11-29 20:56
I've made a whole bunch of updates, all to do with changes in sparse matrices, DataFrames, etc.
This will be merged as 1.0.1. Does not solve the Ex43.3.jl issue yet.

**Comment by goedman** [comment] 2019-11-30 16:46
No luck yet, but I think the problem is the dimensions of the stiffness matrix.

**Comment by goedman** [comment] 2019-12-01 23:15
The problem with Ex43.3.jl was that this problem was not correct as p43 only supports bending. I attempted to add this example many years ago to check an aspect of a directional drilling application (in the Github organization BottomHoleAssemblyAnalysis) and subsequently switched to Frames (as in the Nodal Formulas examples). I should have removed the example then.

I fixed another issue in p43 which caused the forces and moments not to correspond to the book. Not sure at what point I introduced that bug.

Just now a new version has been merged, v1.1.1.

**Closed** 2019-12-09 02:58 UTC
